# Generated by Django 5.0.1 on 2024-01-24 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
